version: "2"
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config:
      config: '.eslint.json'
  duplication:
    enabled: true
    config:
      languages:
        - javascript
checks:
  method-lines:
    config:
      threshold: 40
  method-complexity:
    config:
      threshold: 6
exclude_patterns:
  - ".*"
  - ".*.*"
  - "tasks/**/*.js"
  - "test/**/*.js"
  - "*.json"
  - "**/*.md"
  - "*.js"
  - "LICENSE"
